"""Initial schema

Revision ID: 740d49519a1c
Revises: 
Create Date: 2026-02-12 20:07:34.425534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740d49519a1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('start_page_id', sa.Integer(), nullable=True),
    sa.Column('illustration_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['start_page_id'], ['pages.id'], name='fk_story_start_page', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_ending', sa.Boolean(), nullable=True),
    sa.Column('ending_label', sa.String(length=100), nullable=True),
    sa.Column('illustration_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('choices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('next_page_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['next_page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choices')
    op.drop_table('pages')
    op.drop_table('stories')
    # ### end Alembic commands ###
